//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangDiem
    {
        public int IdMonHoc { get; set; }
        public int IdHocSinh { get; set; }
        public int IdHocKy { get; set; }
        public int IdNamHoc { get; set; }
        public int IdHeSo { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual HeSo HeSo { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
