//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_Management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int IdGiaoVien { get; set; }
        public int IdLopHoc { get; set; }
        public int IdMonHoc { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
